export const parejas = [
    { nombre: "Pareja 1", puntos: 84 },
    { nombre: "Pareja 2", puntos: 99 },
    { nombre: "Pareja 3", puntos: 98 },
    { nombre: "Pareja 4", puntos: 77 },
    { nombre: "Pareja 5", puntos: 95 },
    { nombre: "Pareja 6", puntos: 58 },
    { nombre: "Pareja 7", puntos: 58 },
    { nombre: "Pareja 8", puntos: 72 },
    { nombre: "Pareja 9", puntos: 56 },
    { nombre: "Pareja 10", puntos: 52 },
    { nombre: "Pareja 11", puntos: 98 },
    { nombre: "Pareja 12", puntos: 65 },
    { nombre: "Pareja 13", puntos: 54 },
    { nombre: "Pareja 14", puntos: 57 },
    { nombre: "Pareja 15", puntos: 84 },
    { nombre: "Pareja 16", puntos: 78 },
    { nombre: "Pareja 17", puntos: 72 },
    { nombre: "Pareja 18", puntos: 68 },
    { nombre: "Pareja 19", puntos: 80 },
    { nombre: "Pareja 20", puntos: 73 },
    { nombre: "Pareja 21", puntos: 51 },
    { nombre: "Pareja 22", puntos: 78 },
    { nombre: "Pareja 23", puntos: 98 },
    { nombre: "Pareja 24", puntos: 74 },
    { nombre: "Pareja 25", puntos: 100 },
    { nombre: "Pareja 26", puntos: 90 },
    { nombre: "Pareja 27", puntos: 95 },
    { nombre: "Pareja 28", puntos: 68 },
    { nombre: "Pareja 29", puntos: 93 },
    { nombre: "Pareja 30", puntos: 95 },
    { nombre: "Pareja 31", puntos: 87 },
    { nombre: "Pareja 32", puntos: 60 },
    { nombre: "Pareja 33", puntos: 96 },
    { nombre: "Pareja 34", puntos: 98 },
    { nombre: "Pareja 35", puntos: 61 },
    { nombre: "Pareja 36", puntos: 61 },
    { nombre: "Pareja 37", puntos: 63 },
    { nombre: "Pareja 38", puntos: 59 },
    { nombre: "Pareja 39", puntos: 54 },
    { nombre: "Pareja 40", puntos: 52 },
    { nombre: "Pareja 41", puntos: 61 },
    { nombre: "Pareja 42", puntos: 86 },
    { nombre: "Pareja 43", puntos: 24 },
    { nombre: "Pareja 44", puntos: 94 },
    { nombre: "Pareja 45", puntos: 94 },
    { nombre: "Pareja 46", puntos: 94 },
    { nombre: "Pareja 47", puntos: 94 },
    { nombre: "Pareja 48", puntos: 94 },
]

export const parejasSuma6 = [
    { nombre: "Bonafede - Lavagnoli", puntos: 230 },
    { nombre: "Juarez - Canello", puntos: 360 },
    { nombre: "Argañaraz - Ghelfi", puntos: 500 },
    { nombre: "Mina - Triunfeti", puntos: 360 },
    { nombre: "Salari - Grosso", puntos: 260 },
    { nombre: "Franco - Vignolo", puntos: 660 },
]

export const parejas4 = [
    { nombre: "Culaso - Bosio", puntos: 330 },
    { nombre: "Sanchez - Ferrero", puntos: 900 },
    { nombre: "Picatto - Garnero", puntos: 340 },
    { nombre: "Asselborn - Navarrete", puntos: 290 },
    { nombre: "Soria - Romano", puntos: 380 },
    { nombre: "Galfre - Sogno", puntos: 460 },
]
